### ISSUE TITLE
control flow blocks with local assignments should not be rewritten as postfix expressions

### ISSUE THREAD

**Issue by flavorjones** [kddnewton/syntax_tree#10]
Using `syntax_tree` v1.1.0. Rewriting the following code:

```ruby
n = 1

if (b = n+1) > 1
  puts b
end
```

is rewritten as:

```ruby
n = 1

puts b if (b = n + 1) > 1
```

which will cause an "undefined local variable or method" `NameError` exception to be raised.

**Comment by kddnewton** [comment]
Fixed by 802d6476065f03a3eb11f5171c0c00a15008fcb2 and will be out in `1.1.1`
