### ISSUE TITLE
do no break line when arguments fit into the same line

### ISSUE THREAD

**Issue by dorianmariefr** [kddnewton/syntax_tree#8]
```diff
-  before_action :load_event, only: %i[show edit update destroy copy share delete]
+  before_action :load_event,
+                only: %i[show edit update destroy copy share delete]
```

**Comment by kddnewton** [comment]
On my screen that's exactly 81 characters, which is over the limit, which is why it's breaking. Soon I'll make the width configurable, but for now this is intended.

**Comment by dorianmariefr** [comment]
Yeah oops it’s because it didn’t go through prettier for some reason
